blank_issues_enabled: false
contact_links:
  - name: Questions?
    url: https://github.com/yesoreyeram/grafana-infinity-datasource/discussions/new?category=q-a
    about: Use our Q&A Section in our docs to get answers for your questions
  - name: Showcase
    url: https://github.com/yesoreyeram/grafana-infinity-datasource/discussions/new?category=show-and-tell
    about: Have an inspiring usecase? Use our show & tell section
  - name: Docs
    url: https://yesoreyeram.github.io/grafana-infinity-datasource
    about: Docs
