name: Build & Publish
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - name: Install dependencies
      run: |
        yarn install --frozen-lockfile;
    - name: Test
      run: |
        yarn test;
    - name: Build
      run: |
        yarn build;        
        echo $(date) > dist/LAST_UPDATED;
    - name: Build Docs
      run: |
        yarn docs:build;
        rm -rf docs/dist;
    - name: Publish Updated Type Docs
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: ci build
        push_options: --force
        file_pattern: dist docs
    - uses: actions/setup-go@master
      with:
        go-version: "1.13.3"
    - name: Lint Plugin
      run: |
        git clone https://github.com/grafana/plugin-validator;
        cd ./plugin-validator/cmd/plugincheck;
        go install
        cd ../../;
        plugincheck -url https://github.com/yesoreyeram/grafana-infinity-datasource;